GET http://localhost:8000/list


###

GET http://localhost:8000/list/638e7ecd2219033c14cc9f45


###

POST http://localhost:8000/list
Content-Type: application/json

{
    "movieName": "Batman",
    "movieGenre": "Action",
    "movieRating": "PG-13"
}


###


DELETE  http://localhost:8000/list/638e7ecd2219033c14cc9f45


###


PATCH http://localhost:8000/list/638e802aeeef46da58ac38e7
Content-Type: application/json

{
    "movieName": "Star Wars",
    "movieGenre": "Action/Adventure",
    "movieRating": "PG-13"
}